name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip-ci')"

    steps:
    - name: Checkout Fuxi
      uses: actions/checkout@v2

    - name: Test BPU
      run: sbt "test:runMain bpu.BranchPredictorTest"

    - name: Test CSR
      run: sbt "test:runMain csr.CsrFileTest"

    - name: Test LSU
      run: |
        sbt "test:runMain lsu.AmoExecuteTest"
        sbt "test:runMain lsu.ExclusiveMonitorTest"

    - name: Test MDU
      run: |
        sbt "test:runMain mdu.DividerTest"
        sbt "test:runMain mdu.MultiplierTest"
        sbt "test:runMain mdu.MduTest"

    - name: Test Sim
      run: sbt "test:runMain sim.RamTest"

    - name: Test Stages
      run: |
        sbt "test:runMain core.FetchTest"
        sbt "test:runMain core.DecoderTest"
        sbt "test:runMain core.AluTest"
        sbt "test:runMain core.MemTest"
        sbt "test:runMain core.WriteBackTest"

    - name: Test Bus
      run: sbt "test:runMain bus.TlbTest"

    - name: Test Core
      run: |
        sbt "test:runMain core.CoreTest -if src/test/resources/fib.txt -tf src/test/resources/fib_trace.txt"
        sbt "test:runMain core.CoreTest -if src/test/resources/mdu.txt -tf src/test/resources/mdu_trace.txt"
        sbt "test:runMain core.CoreTest -if src/test/resources/mecall.txt -tf src/test/resources/mecall_trace.txt"
        sbt "test:runMain core.CoreTest -if src/test/resources/secall.txt -tf src/test/resources/secall_trace.txt"
